name: Preview deployment
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Branch to run workflow on"
        default: "master"
        required: true
      customer:
        description: "Customer identifier"
        required: true
        type: choice
        options:
          - gosmart
          - pageplus
          - wfm
          - net10
          - tbv
          - simplemobile
          - safelink
          - tfunbranded
          - straighttalk
          - tracfone
          - visible
          - index1.js
          - index2.js
jobs:
  deploy_feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.target_branch }}
      - name: Get last commit info
        run: |
          echo "PREVIEW_LAST_COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "PREVIEW_LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "PREVIEW_LAST_COMMIT_TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
          echo "PREVIEW_DEPLOYMENT_TIMESTAMP=$(date -u +%s)" >> $GITHUB_ENV
          echo "PREVIEW_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
      - name: Install deps
        run: npm ci
      - name: Deploy preview
        id: deploy
        run: echo "npm run sst:deploy -- ${{ github.event.inputs.customer }} --stage preview"
      - name: simple test
        run: node ${{ github.event.inputs.customer }}
