name: Preview deployment
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Branch to run workflow on"
        default: "master"
        required: true
      customer:
        description: "Customer identifier"
        required: true
        type: choice
        options:
          - gosmart
          - pageplus
          - wfm
          - net10
          - tbv
          - simplemobile
          - safelink
          - tfunbranded
          - straighttalk
          - tracfone
          - visible
          - index1.js
          - index2.js
jobs:
  deploy_feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.target_branch }}
      - name: Get last commit info
        run: |
          echo "LAST_COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "LAST_COMMIT_DATE=$(git log -1 --pretty=%cd --date=iso)" >> $GITHUB_ENV
          echo "DEPLOYMENT_TIME=$(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
      - name: Install deps
        run: npm ci
      - name: Deploy preview
        id: deploy
        run: echo "npm run sst:deploy -- ${{ github.event.inputs.customer }} --stage preview"
      - name: simple test
        run: node ${{ github.event.inputs.customer }}
