name: xtaac deployment
on:
  pull_request:
    paths:
      - src/service-user/**
jobs:
  deploy_user:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: install deps
      run: npm i
